name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      LANG: en_US.utf8
      LIMIT_JEST: yes
      TZ: America/New_York

    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test:cov
      - run: bash <(curl -s https://codecov.io/bash)
